// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:c469cfd3-251b-4aa2-aaac-910a51eae1f5",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_8f3F1RFpt",
    "aws_user_pools_web_client_id": "25lavg814qouqbv461616nld4v"
};


export default awsmobile;
